services:
  backend:
    build: ./backend
    container_name: anidle_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: anidle_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend